[package]
name = "Project Longhorn"
version = "0.1.0"
authors = ["Qubit"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
bitflags = "1.0.1"
x86_64 = "0.1.2"
smoltcp = "0.4.0"
cpuio = "0.2.0"
