[package]
name = "atomOS"
version = "0.1.0"
authors = ["Hydra"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
bitflags = "0.9.1"
x86_64 = "0.1.2"
smoltcp = "0.4.0"
